# SessionStart hook (startup, resume, clear, compact).
# Regenerates the KB index lists, injects Core + Decisions + Mistakes + Standards in full and the
# other Path indexes into context, and marks the session as KB-loaded so the PreToolUse gate opens.
. (Join-Path $PSScriptRoot 'kb-common.ps1')

try {
    $hookInput = Read-HookInput
    $sid    = Get-SessionId $hookInput
    $source = [string](Get-Prop $hookInput 'source'); if (-not $source) { $source = 'startup' }
    $memRel = Get-SessionMemoryRel $sid

    Remove-OldState 7
    try { Update-KbIndexes } catch { }

    $allPaths = Get-PathDirs
    $sb = New-Object System.Text.StringBuilder
    $counts = @()

    [void]$sb.AppendLine('# VOLT KNOWLEDGE BASE (KB) - MANDATORY SESSION CONTEXT')
    [void]$sb.AppendLine("Injected by .claude/hooks/kb-session-start.ps1 on '$source'. Structure: Core -> Path -> Node. Vault: KB/ (Obsidian).")
    [void]$sb.AppendLine('Everything below is now in context and counts as read. Decisions, Mistakes and Standards are complete. Other Paths are listed by node in their index; open a node with the Read tool when it is relevant.')
    [void]$sb.AppendLine()

    if (Test-Path -LiteralPath $CoreFile) {
        [void]$sb.AppendLine('## KB/Core.md')
        [void]$sb.AppendLine((Read-Text $CoreFile).Trim())
        [void]$sb.AppendLine()
    } else {
        [void]$sb.AppendLine('## KB/Core.md IS MISSING. Recreate it (see KB/Standards/kb-node-format.md) before doing anything else.')
        [void]$sb.AppendLine()
    }

    foreach ($p in $allPaths) {
        $name  = $p.Name
        $nodes = Get-Nodes $name
        $idx   = Get-PathIndexFile $name
        $full  = $RequiredPaths -contains $name
        $counts += ('{0} {1}' -f $name, $nodes.Count)
        if ($full) { [void]$sb.AppendLine(('## Path: {0} ({1} nodes, ALL INCLUDED BELOW)' -f $name, $nodes.Count)) }
        else       { [void]$sb.AppendLine(('## Path: {0} ({1} nodes, index only - Read a node when relevant)' -f $name, $nodes.Count)) }
        if (Test-Path -LiteralPath $idx) {
            [void]$sb.AppendLine(('### KB/{0}/{0}.md' -f $name))
            [void]$sb.AppendLine((Read-Text $idx).Trim())
            [void]$sb.AppendLine()
        }
        if ($full) {
            foreach ($n in $nodes) {
                [void]$sb.AppendLine(('### KB/{0}/{1}' -f $name, $n.Name))
                [void]$sb.AppendLine((Read-Text $n.FullName).Trim())
                [void]$sb.AppendLine()
            }
        }
    }

    [void]$sb.AppendLine('## SESSION PROTOCOL (enforced by hooks in .claude/settings.json)')
    [void]$sb.AppendLine(("- Session id: {0}. This session's Memory node: {1}" -f (Get-ShortSid $sid), $memRel))
    [void]$sb.AppendLine('- Write, Edit, shell, Agent and web tools are unlocked because the KB is loaded. Read, Glob and Grep are always allowed.')
    [void]$sb.AppendLine(("- Any turn that changes files, runs a non-read-only command or uses web tools cannot end until {0} has been created or updated with the Write or Edit tool. Keep it compact: what / why / how / outcome / open. Not a log." -f $memRel))
    [void]$sb.AppendLine('- One node per thing: new mistake -> KB/Mistakes, new research -> KB/Research, new convention -> KB/Standards, plan -> KB/Planning. Use the template in that Path''s index note. Never merge two things into one node. Never edit another session''s Memory node.')
    [void]$sb.AppendLine('- git commit / push / merge / rebase / cherry-pick / revert and PR creation are blocked. The user reviews and commits.')
    [void]$sb.AppendLine('- Nothing is written on main: Write, Edit and non-read-only shell commands are denied while the working tree is on main. Before the first file change run git switch -c <name> on its own (feature/<system>, fix/<x>, docs/<x>, or CU-<taskid>_<compactname>_<author>). Gitignored paths such as KB/ are exempt.')
    [void]$sb.AppendLine('- Lists between kb:auto markers are regenerated by hooks; do not hand-edit them.')

    Touch-State $sid 'kb-loaded'

    $ctx = $sb.ToString()
    $kb  = [math]::Round([System.Text.Encoding]::UTF8.GetByteCount($ctx) / 1024)
    $msg = 'KB loaded into context (' + ($counts -join ', ') + ("; {0} KB). Session memory node: {1}" -f $kb, $memRel)
    if ($kb -gt 120) { $msg += ' WARNING: KB injection exceeds 120 KB. Consider consolidating Standards nodes.' }

    Write-HookJson @{
        hookSpecificOutput = @{ hookEventName = 'SessionStart'; additionalContext = $ctx }
        systemMessage      = $msg
    }
    exit 0
} catch {
    $err = $_.Exception.Message
    Write-HookJson @{
        systemMessage      = ('KB SessionStart hook FAILED: ' + $err + '. The write gate stays closed until KB/Core.md, KB/Decisions, KB/Mistakes and KB/Standards are read with the Read tool.')
        hookSpecificOutput = @{ hookEventName = 'SessionStart'; additionalContext = ('KB SessionStart hook failed (' + $err + '). Before any work: use the Read tool on KB/Core.md and on every .md file in KB/Decisions, KB/Mistakes and KB/Standards. Write, Edit, shell, Agent and web tools are denied until then.') }
    }
    exit 0
}
